# Generated by Django 3.1.4 on 2021-01-08 06:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField(null=True)),
                ('tel', models.CharField(max_length=11, null=True)),
                ('user_type', models.TextField(default='user')),
                ('last_login_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
            managers=[
                ('object', account.models.UserManager()),
            ],
        ),
    ]
